"""
Django settings for company_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-this-key-before-deploy-1234567890'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # В Docker разрешаем все хосты для простоты

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd PARTY APPS (ДО ваших приложений)
    'rest_framework',
    'django_filters',
    'corsheaders',  # Для CORS
    'ckeditor',  # Для редактора текста
    'drf_yasg',  # Для Swagger документации

    # YOUR APPS (ВАШИ ПРИЛОЖЕНИЯ)
    'employees',  # Должно быть первым, так как содержит модель пользователя
    'workplaces',
]

MIDDLEWARE = [
    # CORS middleware должен быть наверху!
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'company_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'company_project.wsgi.application'

# Database (Переводим на PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'company_db',  # Имя БД в контейнере PostgreSQL
        'USER': 'postgres',  # Пользователь БД в контейнере
        'PASSWORD': 'postgres',  # Пароль пользователя в контейнере
        'HOST': 'db',  # Имя сервиса из docker-compose.yml
        'PORT': 5432,
    }
}

# Password validation and other settings...
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
]

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
# Настройка для правильного кэширования статики в продакшене
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media files (Загружаемые изображения)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'employees.CustomUser'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/employees/'

# --- DRF SETTINGS (Django REST Framework) ---
REST_FRAMEWORK = {
    # Используем JWT для аутентификации
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Пагинация (10 на страницу)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
}

# --- CORS HEADERS ---
CORS_ALLOW_ALL_ORIGINS = True  # Разрешаем запросы с любого домена

# --- CKEDITOR SETTINGS ---
CKEDITOR_CONFIGS = {
    'default': {
        # Настройка высоты редактора по умолчанию
        'height': 300,
    },
}

# --- SWAGGER SETTINGS ---
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        # Добавляем поддержку JWT токена прямо в Swagger UI
        'Token Auth': {'type': 'apiKey', 'name': 'Authorization', 'in': 'header'},
    }
}