# Generated by Django 6.0.4 on 2026-04-28 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема на работу'),
        ),
    ]
